ZSH=$HOME/.oh-my-zsh

# You can change the theme with another one:
#   https://github.com/robbyrussell/oh-my-zsh/wiki/themes
ZSH_THEME="robbyrussell"
plugins=(fzf git vi-mode gcloud kubectl kube-ps1 gitfast last-working-dir common-aliases zsh-syntax-highlighting history-substring-search z docker docker-compose asdf doctl helm terraform)

# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"

unalias rm # No interactive rm by default (brought by plugins/common-aliases)
fpath+=~/.zfunc
# Rails and Ruby uses the local `bin` folder to store binstubs.
# So instead of running `bin/rails` like the doc says, just run `rails`
# Same for `./node_modules/.bin` and nodejs
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"

# Store your own aliases in the ~/.aliases file and load the here.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES
export BUNDLER_EDITOR="nvim"
export EDITOR="nvim"
export ERL_AFLAGS="-kernel shell_history enabled"
export PATH=$PATH:$HOME/.toolbox/bin
source "$HOME/.cargo/env"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

function proxyssh {
    # The first argument is the 'stepping stone',
    # the second is the target to ssh into
    ssh -o proxyCommand="ssh -W %h:%p $1" $2
}

function dmskey () {
    # The first argument the key
    # the second is the region, iad, dub, pdx (default iad)
    AWS_PAGER=""
    REGION="${2:-iad}"
    if [ $REGION = "dub" ]; then
        ACCOUNT="389629145810"
        AWS_REGION="eu-west-1"
    elif [ $REGION = "pdx" ]; then
        ACCOUNT="681855990469"
        AWS_REGION="us-west-2"
    else
        ACCOUNT="917838938311"
        AWS_REGION="us-east-1"
    fi
    echo "Querying account ${ACCOUNT} in aws region ${AWS_REGION} for key ${1}"
    ada credentials update --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE --account=$ACCOUNT --profile=dms --once
    aws dynamodb get-item --profile dms --region $AWS_REGION --table-name transformation-scripts --key "{\"key\": {\"S\": \"$1\"}}" | jq  '.Item.value.B' | tr -d '"' | base64 --decode | xmllint --format -
}

function kw() {
    echo "Logging into kinit and mwinit"
    kinit --keychain
    { security find-generic-password -a $USER -s 'amazon_login' -w; read -E } | mwinit -o
}

# Make CTRL-Z background things and unbackground them.
function fg-bg() {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
  else
    zle push-input
  fi
}
zle -N fg-bg
bindkey '^Z' fg-bg

autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^x' edit-command-line

[ -f "/Users/arakov/.ghcup/env" ] && source "/Users/arakov/.ghcup/env" # ghcup-env
