---

- hosts: all

  tasks:
    - pip:
        extra_args: "--user"
        name: '{{ item }}'
        state: latest
      with_items:
        - neovim
        - ansible-lint
        - yamllint
        - bashate
        - sexpdata
        - websocket-client
        - jedi
        - psutil
        - setproctitle
        - python-language-server
        - rope
        - isort
        - black
      tags:
        - python

    - gem:
        name: "{{ item }}"
        state: latest
        user_install: false
      become: true
      with_items:
        - rake
        - neovim
        - mdl
        - haml-lint
        - sqlint
        - rubocop
        - rubocop-rspec
        - solargraph
        - fastri
        - slim_lint
        - brakeman
        - rails_best_practices
        - reek
        - rspec
        - pry
        - pry-byebug
        - colored
        - http
        - bunlder
      tags:
        - ruby

    - npm:
        name: "{{ item }}"
        state: latest
        global: true
      become: true
      with_items:
        - yaml-language-server
        - sql-language-server
        - prettier
        - typescript
        - typings
        - pug-lint
        - livedown
        - js-yaml
        - import-js
        - stylelint
        - js-beautify
        - jsonlint
        - eslint
        - neovim
        - babel-eslint
        - javascript-typescript-langserver
        - eslint-plugin-jest
        - eslint-plugin-flowtype
        - eslint-plugin-import
        - eslint-import-resolver-webpack
        - eslint-plugin-markdown
        - eslint-plugin-jsx-a11y
        - eslint-config-airbnb
        - eslint-config-airbnb-base
        - eslint-plugin-react
        - eslint-plugin-babel
      tags:
        - npm
