---

- hosts: localhost

  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: true

    - name: Install github gh apt key
      apt_key:
        id: C99B11DEB97541F0
        keyserver: keyserver.ubuntu.com
        state: present

    - name: Add gh Repository
      apt_repository:
        repo: https://cli.github.com/packages
        state: present

    - name: Install required system packages
      apt: name={{ item }} state=present update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'zsh', 'curl', 'vim', 'imagemagic', 'jq', 'build-essential', 'tklib', 'zlib1g-dev', 'libssl-dev', 'libffi-dev', 'libxml2', 'libxml2-dev', 'libxslt1-dev', 'libreadline-dev', 'tree', 'ncdu', 'htop', 'tig', 'hub', 'gh', 'neovim']

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker engine
      apt: name={{ item }} state=present update_cache=yes
      loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: Ubuntu inotify
      become: true
      command: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

