---

- hosts: all
  become: true
  tags: setup

  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: true

    - name: Install required system packages
      apt: name={{ item }} state=present update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'zsh', 'curl', 'vim', 'jq', 'build-essential', 'tklib', 'zlib1g-dev', 'libssl-dev', 'libffi-dev', 'libxml2', 'libxml2-dev', 'libxslt1-dev', 'libreadline-dev', 'tree', 'ncdu', 'htop', 'tig', 'neovim', 'imagemagick', 'dirmngr', 'gpg', 'gcc', 'fzf', 'bat', 'silversearcher-ag']

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker engine
      apt: name={{ item }} state=present update_cache=yes
      loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: Install docker-compose
      remote_user: ubuntu
      get_url:
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

    - name: Ubuntu inotify
      become: true
      command: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Reboot
      reboot:
        reboot_timeout: 3600

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: root


