---

- hosts: all
  become: true
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: true

    - name: Install required system packages
      apt: name={{ item }} state=present update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'zsh', 'curl', 'vim', 'jq', 'build-essential', 'tklib', 'zlib1g-dev', 'libssl-dev', 'libffi-dev', 'libxml2', 'libxml2-dev', 'libxslt1-dev', 'libreadline-dev', 'tree', 'ncdu', 'htop', 'tig', 'neovim', 'imagemagick', 'dirmngr', 'gpg', 'gcc', 'fzf', 'bat', 'silversearcher-ag']


- name: Install zsh
  hosts: all
  become: yes

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: root

- name: install and setup docker
  hosts: all
  become: yes

  roles:
    - name: geerlingguy.docker
      vars:
        docker_install_compose: true
    - name: markosamuli.asdf
      vars:
        asdf_init_shell: true

- name: Install asdf and plugins
  hosts: all
  roles:
    - role: markosamuli.asdf
      vars:
        asdf_plugins:
          - name: "nodejs"
            versions: ["16.13.1"]
            global: "16.13.1"

          - name: "ruby"
            versions: ["3.0.3"]
            global: "3.0.3"

          - name: "python"
            versions: ["3.10.0", "2.7.18"]

- name: update watches
  hosts: all
  become: true
  tasks:
    - name: Ubuntu inotify
      command: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Reboot
      reboot:
        reboot_timeout: 3600
