---

- hosts: all

  tasks:
    - name: Clone rbenv
      git:
        repo: https://github.com/rbenv/rbenv.git
        dest: ~/.rbenv

    - name: clone ruby build
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build

    - name: Install ruby
      command: rbenv install 2.7.2

    - name: Global ruby
      command: rbenv global 2.7.2

    - name: Install nvm
      command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | zsh

    - name: Install node
      command: nvm install 14.15.0
