---

- hosts: localhost
  tags: setup


  tasks:
    - name: Creat dir code
      file:
        path: ~/code
        state: directory

    - name: Create dir with my folder
      file:
        path: ~/code/artemrakov
        state: directory

    - name: Copy my files
      git:
        repo: https://github.com/ArtemRakov/dotfiles.git
        dest: ~/code/artemrakov

    - name: Run installation script
      script:
        command: files/install.sh

    - name: Create .config for neovim
      file:
        path: ~/.config
        state: directory

    - name: Link vimrc to neovim
      file:
        src: files/vimrc
        dest: ~/.config/nvim
        state: link

    - name: Link coc settings
      file:
        src: files/coc-settings.json
        dest: ~/.config/nvim
        state: link

