---

- hosts: all
  tags: setup


  tasks:
    - name: Creat dir code
      file:
        path: ~/code
        state: directory

    - name: Create dir with my folder
      file:
        path: ~/code/artemrakov
        state: directory

    - name: Copy my files
      git:
        repo: https://github.com/ArtemRakov/dotfiles.git
        dest: ~/code/artemrakov/dotfiles

    - name: Run installation script
      shell: 'cd ~/code/artemrakov/dotfiles/files && zsh install.sh'
      ignore_errors: true
