---

- hosts: all
  tags: setup


  tasks:
    - name: Creat dir code
      file:
        path: ~/code
        state: directory

    - name: Copy my files
      git:
        repo: git@github.com:ArtemRakov/dotfiles.git
        dest: ~/code/dotfiles

    - name: Run installation script
      shell: 'cd ~/code/dotfiles/files && zsh install.sh'
      ignore_errors: true

    - name: Create nvim dir
      file:
        dest: ~/.config/nvim
        state: directory

    - name: link vimrc
      file:
        src: "~/code/dotfiles/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link

    - name: Install vim plug
      get_url:
        force: yes
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
