---

- hosts: all
  tags: setup


  tasks:
    - name: Run installation script
      shell: 'cd ~/code/dotfiles/files && zsh install.sh'
      ignore_errors: true

    - name: Create nvim dir
      file:
        dest: ~/.config/nvim
        state: directory

    - name: link vimrc
      file:
        src: "~/code/dotfiles/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link
        
    - name: link coc-settings.json
      file:
        src: "~/code/dotfiles/files/coc-settings.json"
        dest: ~/.config/nvim/coc-settings.json
        state: link
               
    - name: Autoload nvim
      file: path=~/.local/share/nvim/site/autoload state=directory recurse=Yes
      with_items:
        - autoload

    - name: Load vim plug
      get_url:
        force: yes
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
