---

- hosts: all
  tags: setup


  tasks:
    - name: Creat dir code
      file:
        path: ~/code
        state: directory

    - name: Create dir with my folder
      file:
        path: ~/code/artemrakov
        state: directory

    - name: Copy my files
      git:
        repo: https://github.com/ArtemRakov/dotfiles.git
        dest: ~/code/artemrakov/dotfiles

    - name: Run installation script
      command: zsh ~/code/artemrakov/dotfiles/files/install.sh

    - name: Create .config for neovim
      file:
        path: ~/.config
        state: directory

    - name: Link vimrc to neovim
      file:
        src: ~/code/artemrakov/dotfiles/files/init.vim
        dest: ~/.config/nvim/init.vim
        state: link

    - name: Link coc settings
      file:
        src: ~/code/artemrakov/dotfiles/files/coc-settings.json
        dest: ~/.config/nvim/coc-settings.json
        state: link

